name: Deploy prod

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/gabrycina/redazione:latest
          cache-from: type=registry,ref=ghcr.io/gabrycina/redazione:cache
          cache-to: mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=ghcr.io/gabrycina/redazione:cache
